[2024-06-26 23:54:43,916] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_2.process_text manual__2024-06-26T23:49:32.605042+00:00 [queued]>
[2024-06-26 23:54:43,930] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_2.process_text manual__2024-06-26T23:49:32.605042+00:00 [queued]>
[2024-06-26 23:54:43,930] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 23:54:43,930] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2024-06-26 23:54:43,931] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-06-26 23:54:43,955] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-26 23:49:32.605042+00:00
[2024-06-26 23:54:43,961] {standard_task_runner.py:52} INFO - Started process 5673 to run task
[2024-06-26 23:54:43,979] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_2', 'process_text', 'manual__2024-06-26T23:49:32.605042+00:00', '--job-id', '3172', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_2.py', '--cfg-path', '/tmp/tmpb_rc31y3', '--error-file', '/tmp/tmpaxp46jql']
[2024-06-26 23:54:43,983] {standard_task_runner.py:77} INFO - Job 3172: Subtask process_text
[2024-06-26 23:54:44,089] {logging_mixin.py:109} INFO - Running <TaskInstance: text_processing_dag_2.process_text manual__2024-06-26T23:49:32.605042+00:00 [running]> on host cf249bbdc0d0
[2024-06-26 23:54:44,214] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=text_processing_dag_2
AIRFLOW_CTX_TASK_ID=process_text
AIRFLOW_CTX_EXECUTION_DATE=2024-06-26T23:49:32.605042+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-06-26T23:49:32.605042+00:00
[2024-06-26 23:54:45,940] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 17, in process_text
    df = pd.read_json(input_path)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 618, in read_json
    result = json_reader.read()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 755, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 777, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 886, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 1119, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2024-06-26 23:54:45,981] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=text_processing_dag_2, task_id=process_text, execution_date=20240626T234932, start_date=20240626T235443, end_date=20240626T235445
[2024-06-26 23:54:46,088] {standard_task_runner.py:92} ERROR - Failed to execute job 3172 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 17, in process_text
    df = pd.read_json(input_path)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/util/_decorators.py", line 296, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 618, in read_json
    result = json_reader.read()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 755, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 777, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 886, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/json/_json.py", line 1119, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2024-06-26 23:54:46,124] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-06-26 23:54:46,214] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
