[2024-06-25 04:54:55,358] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-06-25T04:52:59.475252+00:00 [queued]>
[2024-06-25 04:54:55,435] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-06-25T04:52:59.475252+00:00 [queued]>
[2024-06-25 04:54:55,436] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,436] {taskinstance.py:1244} INFO - Starting attempt 2 of 3
[2024-06-25 04:54:55,436] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,570] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-25 04:52:59.475252+00:00
[2024-06-25 04:54:55,633] {standard_task_runner.py:52} INFO - Started process 3374 to run task
[2024-06-25 04:54:55,695] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_1', 'process_text', 'manual__2024-06-25T04:52:59.475252+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_1.py', '--cfg-path', '/tmp/tmp86z52ndt', '--error-file', '/tmp/tmpyh6wk68t']
[2024-06-25 04:54:55,773] {standard_task_runner.py:77} INFO - Job 147: Subtask process_text
[2024-06-25 04:54:56,037] {standard_task_runner.py:92} ERROR - Failed to execute job 147 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 287, in task_run
    ti = _get_ti(task, args.execution_date_or_run_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 86, in _get_ti
    dag_run = _get_dag_run(task.dag, exec_date_or_run_id, create_if_necssary, session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 80, in _get_dag_run
    ) from None
airflow.exceptions.DagRunNotFound: DagRun for text_processing_dag_1 with run_id or execution_date of 'manual__2024-06-25T04:52:59.475252+00:00' not found
[2024-06-25 04:54:56,085] {local_task_job.py:154} INFO - Task exited with return code 1
