[2024-07-12 00:27:03,720] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-07-12T00:26:47.486815+00:00 [queued]>
[2024-07-12 00:27:03,793] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_1.process_text manual__2024-07-12T00:26:47.486815+00:00 [queued]>
[2024-07-12 00:27:03,793] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-07-12 00:27:03,793] {taskinstance.py:1244} INFO - Starting attempt 1 of 2
[2024-07-12 00:27:03,793] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-07-12 00:27:03,902] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-07-12 00:26:47.486815+00:00
[2024-07-12 00:27:03,908] {standard_task_runner.py:52} INFO - Started process 4740 to run task
[2024-07-12 00:27:03,940] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_1', 'process_text', 'manual__2024-07-12T00:26:47.486815+00:00', '--job-id', '3206', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_1.py', '--cfg-path', '/tmp/tmp84t8bc1y', '--error-file', '/tmp/tmprkrarptx']
[2024-07-12 00:27:03,986] {standard_task_runner.py:77} INFO - Job 3206: Subtask process_text
[2024-07-12 00:27:04,320] {logging_mixin.py:109} INFO - Running <TaskInstance: text_processing_dag_1.process_text manual__2024-07-12T00:26:47.486815+00:00 [running]> on host cf249bbdc0d0
[2024-07-12 00:27:04,870] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=text_processing_dag_1
AIRFLOW_CTX_TASK_ID=process_text
AIRFLOW_CTX_EXECUTION_DATE=2024-07-12T00:26:47.486815+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-12T00:26:47.486815+00:00
[2024-07-12 00:27:10,777] {logging_mixin.py:109} INFO - Index(['date', 'time', 'messages', 'video_links', 'video_durations'], dtype='object')
[2024-07-12 00:28:37,225] {local_task_job.py:212} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-07-12 00:28:37,249] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 4740. PIDs of all processes in the group: [4740]
[2024-07-12 00:28:37,249] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 4740
[2024-07-12 00:28:37,252] {taskinstance.py:1413} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-12 00:28:37,405] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 123, in process_text
    keywords = extract_keywords(i)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 106, in extract_keywords
    doc = nlp(text)
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/language.py", line 1047, in __call__
    error_handler(name, proc, [doc], e)
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/util.py", line 1724, in raise_error
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/language.py", line 1042, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "spacy/pipeline/trainable_pipe.pyx", line 56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/util.py", line 1724, in raise_error
    raise e
  File "spacy/pipeline/trainable_pipe.pyx", line 52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/pipeline/tok2vec.py", line 126, in predict
    tokvecs = self.model.predict(docs)
  File "/home/airflow/.local/lib/python3.6/site-packages/thinc/model.py", line 334, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/airflow/.local/lib/python3.6/site-packages/thinc/layers/chain.py", line 56, in forward
    X = Y
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-07-12 00:28:37,453] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=text_processing_dag_1, task_id=process_text, execution_date=20240712T002647, start_date=20240712T002703, end_date=20240712T002837
[2024-07-12 00:28:37,563] {standard_task_runner.py:92} ERROR - Failed to execute job 3206 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 123, in process_text
    keywords = extract_keywords(i)
  File "/opt/airflow/dags/../scripts/text_processing.py", line 106, in extract_keywords
    doc = nlp(text)
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/language.py", line 1047, in __call__
    error_handler(name, proc, [doc], e)
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/util.py", line 1724, in raise_error
    raise e
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/language.py", line 1042, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "spacy/pipeline/trainable_pipe.pyx", line 56, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/util.py", line 1724, in raise_error
    raise e
  File "spacy/pipeline/trainable_pipe.pyx", line 52, in spacy.pipeline.trainable_pipe.TrainablePipe.__call__
  File "/home/airflow/.local/lib/python3.6/site-packages/spacy/pipeline/tok2vec.py", line 126, in predict
    tokvecs = self.model.predict(docs)
  File "/home/airflow/.local/lib/python3.6/site-packages/thinc/model.py", line 334, in predict
    return self._func(self, X, is_train=False)[0]
  File "/home/airflow/.local/lib/python3.6/site-packages/thinc/layers/chain.py", line 56, in forward
    X = Y
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1415, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-07-12 00:28:37,695] {process_utils.py:70} INFO - Process psutil.Process(pid=4740, status='terminated', exitcode=1, started='00:27:03') (4740) terminated with exit code 1
