[2024-06-25 04:54:55,350] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_2.process_text scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-25 04:54:55,389] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: text_processing_dag_2.process_text scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-25 04:54:55,396] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,396] {taskinstance.py:1244} INFO - Starting attempt 3 of 4
[2024-06-25 04:54:55,396] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2024-06-25 04:54:55,477] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): process_text> on 2024-06-18 00:00:00+00:00
[2024-06-25 04:54:55,524] {standard_task_runner.py:52} INFO - Started process 3372 to run task
[2024-06-25 04:54:55,635] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'text_processing_dag_2', 'process_text', 'scheduled__2024-06-18T00:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dag_text_processing_2.py', '--cfg-path', '/tmp/tmped4rtr6l', '--error-file', '/tmp/tmp9tpyaawt']
[2024-06-25 04:54:55,670] {standard_task_runner.py:77} INFO - Job 150: Subtask process_text
[2024-06-25 04:54:55,987] {standard_task_runner.py:92} ERROR - Failed to execute job 150 for task process_text
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 287, in task_run
    ti = _get_ti(task, args.execution_date_or_run_id)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 86, in _get_ti
    dag_run = _get_dag_run(task.dag, exec_date_or_run_id, create_if_necssary, session)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 80, in _get_dag_run
    ) from None
airflow.exceptions.DagRunNotFound: DagRun for text_processing_dag_2 with run_id or execution_date of 'scheduled__2024-06-18T00:00:00+00:00' not found
[2024-06-25 04:54:56,036] {local_task_job.py:154} INFO - Task exited with return code 1
